-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 09:10:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SACEAM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SACEAM` ;

-- -----------------------------------------------------
-- Schema SACEAM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SACEAM` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish2_ci ;
USE `SACEAM` ;

-- -----------------------------------------------------
-- Table `ACUDIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACUDIENTE` ;

CREATE TABLE IF NOT EXISTS `ACUDIENTE` (
  `acudiente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`acudiente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `AULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AULA` ;

CREATE TABLE IF NOT EXISTS `AULA` (
  `aula_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`aula_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `CIUDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CIUDAD` ;

CREATE TABLE IF NOT EXISTS `CIUDAD` (
  `ciudad_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `PAIS_pais_id` INT NOT NULL,
  PRIMARY KEY (`ciudad_id`),
  CONSTRAINT `fk_CIUDAD_PAIS1`
    FOREIGN KEY (`PAIS_pais_id`)
    REFERENCES `PAIS` (`pais_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_CIUDAD_PAIS1_idx` ON `CIUDAD` (`PAIS_pais_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DECANO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DECANO` ;

CREATE TABLE IF NOT EXISTS `DECANO` (
  `decano_id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `facultad_id` INT NOT NULL,
  PRIMARY KEY (`decano_id`),
  CONSTRAINT `fk_DECANO_PERSONA`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PERSONA` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DECANO_FACULTAD`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `FACULTAD` (`facultad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DECANO_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_DECANO_PERSONA` ON `DECANO` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_DECANO_FACULTAD` ON `DECANO` (`facultad_id` ASC) VISIBLE;

CREATE INDEX `fk_DECANO_USUARIO` ON `DECANO` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_DECANO_PERSONA` ON `DECANO` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_DECANO_FACULTAD` ON `DECANO` (`facultad_id` ASC) VISIBLE;

CREATE INDEX `fk_DECANO_USUARIO` ON `DECANO` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DEPARTAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEPARTAMENTO` ;

CREATE TABLE IF NOT EXISTS `DEPARTAMENTO` (
  `departamento_id` INT NOT NULL AUTO_INCREMENT,
  `pais_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`departamento_id`),
  CONSTRAINT `fk_DEPARTAMENTO_PAIS`
    FOREIGN KEY (`pais_id`)
    REFERENCES `PAIS` (`pais_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_DEPARTAMENTO_PAIS` ON `DEPARTAMENTO` (`pais_id` ASC) VISIBLE;

CREATE INDEX `fk_DEPARTAMENTO_PAIS` ON `DEPARTAMENTO` (`pais_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DIRECTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DIRECTOR` ;

CREATE TABLE IF NOT EXISTS `DIRECTOR` (
  `director_id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `facultad_id` INT NOT NULL,
  PRIMARY KEY (`director_id`),
  CONSTRAINT `fk_DIRECTOR_PERSONA`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PERSONA` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECTOR_FACULTAD`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `FACULTAD` (`facultad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECTOR_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_DIRECTOR_PERSONA` ON `DIRECTOR` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_DIRECTOR_FACULTAD` ON `DIRECTOR` (`facultad_id` ASC) VISIBLE;

CREATE INDEX `fk_DIRECTOR_USUARIO` ON `DIRECTOR` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_DIRECTOR_PERSONA` ON `DIRECTOR` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_DIRECTOR_FACULTAD` ON `DIRECTOR` (`facultad_id` ASC) VISIBLE;

CREATE INDEX `fk_DIRECTOR_USUARIO` ON `DIRECTOR` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `ESTUDIANTE` (
  `estudiante_id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `acudiente_id` INT NOT NULL,
  `programa_academico_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`estudiante_id`),
  CONSTRAINT `fk_ESTUDIANTE_PERSONA`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PERSONA` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_ACUDIENTE`
    FOREIGN KEY (`acudiente_id`)
    REFERENCES `ACUDIENTE` (`acudiente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_PROGRAMA_ACADEMICO`
    FOREIGN KEY (`programa_academico_id`)
    REFERENCES `PROGRAMA_ACADEMICO` (`programa_academico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_ESTUDIANTE_PERSONA` ON `ESTUDIANTE` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_ACUDIENTE` ON `ESTUDIANTE` (`acudiente_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_PROGRAMA_ACADEMICO` ON `ESTUDIANTE` (`programa_academico_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_USUARIO` ON `ESTUDIANTE` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_PERSONA` ON `ESTUDIANTE` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_ACUDIENTE` ON `ESTUDIANTE` (`acudiente_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_PROGRAMA_ACADEMICO` ON `ESTUDIANTE` (`programa_academico_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_USUARIO` ON `ESTUDIANTE` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ESTUDIANTE_GRUPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ESTUDIANTE_GRUPO` ;

CREATE TABLE IF NOT EXISTS `ESTUDIANTE_GRUPO` (
  `estudiante_grupo_id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`estudiante_grupo_id`),
  CONSTRAINT `fk_ESTUDIANTE_GRUPO_ESTUDIANTE`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `ESTUDIANTE` (`estudiante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_GRUPO_GRUPO`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `GRUPO` (`grupo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_ESTUDIANTE_GRUPO_ESTUDIANTE` ON `ESTUDIANTE_GRUPO` (`estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_GRUPO_GRUPO` ON `ESTUDIANTE_GRUPO` (`grupo_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_GRUPO_ESTUDIANTE` ON `ESTUDIANTE_GRUPO` (`estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_ESTUDIANTE_GRUPO_GRUPO` ON `ESTUDIANTE_GRUPO` (`grupo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FACULTAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FACULTAD` ;

CREATE TABLE IF NOT EXISTS `FACULTAD` (
  `facultad_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`facultad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `GRUPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRUPO` ;

CREATE TABLE IF NOT EXISTS `GRUPO` (
  `grupo_id` INT NOT NULL AUTO_INCREMENT,
  `materia_id` INT NOT NULL,
  `profesor_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`),
  CONSTRAINT `fk_GRUPO_MATERIA`
    FOREIGN KEY (`materia_id`)
    REFERENCES `MATERIA` (`materia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GRUPO_PROFESOR`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `PROFESOR` (`profesor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_GRUPO_MATERIA` ON `GRUPO` (`materia_id` ASC) VISIBLE;

CREATE INDEX `fk_GRUPO_PROFESOR` ON `GRUPO` (`profesor_id` ASC) VISIBLE;

CREATE INDEX `fk_GRUPO_MATERIA` ON `GRUPO` (`materia_id` ASC) VISIBLE;

CREATE INDEX `fk_GRUPO_PROFESOR` ON `GRUPO` (`profesor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `HORARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HORARIO` ;

CREATE TABLE IF NOT EXISTS `HORARIO` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `aula_id` INT NOT NULL,
  `dia` VARCHAR(100) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`horario_id`),
  CONSTRAINT `fk_HORARIO_GRUPO`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `GRUPO` (`grupo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORARIO_AULA`
    FOREIGN KEY (`aula_id`)
    REFERENCES `AULA` (`aula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_HORARIO_GRUPO` ON `HORARIO` (`grupo_id` ASC) VISIBLE;

CREATE INDEX `fk_HORARIO_AULA` ON `HORARIO` (`aula_id` ASC) VISIBLE;

CREATE INDEX `fk_HORARIO_GRUPO` ON `HORARIO` (`grupo_id` ASC) VISIBLE;

CREATE INDEX `fk_HORARIO_AULA` ON `HORARIO` (`aula_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MATERIA` ;

CREATE TABLE IF NOT EXISTS `MATERIA` (
  `materia_id` INT NOT NULL AUTO_INCREMENT,
  `programa_academico_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `creditos` INT NOT NULL,
  PRIMARY KEY (`materia_id`),
  CONSTRAINT `fk_MATERIA_PROGRAMA_ACADEMICO`
    FOREIGN KEY (`programa_academico_id`)
    REFERENCES `PROGRAMA_ACADEMICO` (`programa_academico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_MATERIA_PROGRAMA_ACADEMICO` ON `MATERIA` (`programa_academico_id` ASC) VISIBLE;

CREATE INDEX `fk_MATERIA_PROGRAMA_ACADEMICO` ON `MATERIA` (`programa_academico_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PAIS` ;

CREATE TABLE IF NOT EXISTS `PAIS` (
  `pais_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `CIUDAD_ciudad_id` INT NOT NULL,
  PRIMARY KEY (`pais_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `PERSONA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERSONA` ;

CREATE TABLE IF NOT EXISTS `PERSONA` (
  `persona_id` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`persona_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE UNIQUE INDEX `identificacion_UNIQUE` ON `PERSONA` (`identificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PROFESOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESOR` ;

CREATE TABLE IF NOT EXISTS `PROFESOR` (
  `profesor_id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `especialidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`profesor_id`),
  CONSTRAINT `fk_PROFESOR_PERSONA`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PERSONA` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESOR_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_PROFESOR_PERSONA` ON `PROFESOR` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_PROFESOR_USUARIO` ON `PROFESOR` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_PROFESOR_PERSONA` ON `PROFESOR` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_PROFESOR_USUARIO` ON `PROFESOR` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PROGRAMA_ACADEMICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROGRAMA_ACADEMICO` ;

CREATE TABLE IF NOT EXISTS `PROGRAMA_ACADEMICO` (
  `programa_academico_id` INT NOT NULL AUTO_INCREMENT,
  `facultad_id` INT NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `duracion` INT NOT NULL COMMENT 'Duración en semestres o años',
  `titulo_otorgado` VARCHAR(100) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`programa_academico_id`),
  CONSTRAINT `fk_PROGRAMA_ACADEMICO_FACULTAD`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `FACULTAD` (`facultad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE UNIQUE INDEX `codigo_UNIQUE` ON `PROGRAMA_ACADEMICO` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_PROGRAMA_ACADEMICO_FACULTAD` ON `PROGRAMA_ACADEMICO` (`facultad_id` ASC) VISIBLE;

CREATE INDEX `fk_PROGRAMA_ACADEMICO_FACULTAD` ON `PROGRAMA_ACADEMICO` (`facultad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SECRETARIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SECRETARIA` ;

CREATE TABLE IF NOT EXISTS `SECRETARIA` (
  `secretaria_id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `programa_academico_id` INT NOT NULL,
  PRIMARY KEY (`secretaria_id`),
  CONSTRAINT `fk_SECRETARIA_PERSONA`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PERSONA` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECRETARIA_PROGRAMA_ACADEMICO`
    FOREIGN KEY (`programa_academico_id`)
    REFERENCES `PROGRAMA_ACADEMICO` (`programa_academico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECRETARIA_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE INDEX `fk_SECRETARIA_PERSONA` ON `SECRETARIA` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_SECRETARIA_PROGRAMA_ACADEMICO` ON `SECRETARIA` (`programa_academico_id` ASC) VISIBLE;

CREATE INDEX `fk_SECRETARIA_USUARIO` ON `SECRETARIA` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_SECRETARIA_PERSONA` ON `SECRETARIA` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_SECRETARIA_PROGRAMA_ACADEMICO` ON `SECRETARIA` (`programa_academico_id` ASC) VISIBLE;

CREATE INDEX `fk_SECRETARIA_USUARIO` ON `SECRETARIA` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` ENUM('Estudiante', 'Profesor', 'Secretaria', 'Director', 'Decano') NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish2_ci;

CREATE UNIQUE INDEX `username_UNIQUE` ON `USUARIO` (`username` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
